micronaut:
  security:
    oauth2:
      clients:
        keycloak:
          openid:
            issuer: 'http://localhost:8082/realms/petclinic'

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

kafka:
  bootstrap:
    servers: localhost:9092

